version: '3'
services:
  product_service:
    build: ./product_service
    ports:
      - "5001:5001"
  
  order_service:
    build: ./order_service
    ports:
      - "5002:5002"

  user_service:
    build: ./user_service
    ports:
      - "5003:5003" 
    environment:
      - FLASK_ENV=development 
